name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Build
      run: wasm-pack build --target web
    - name: Add Artifacts
      run: git add -f pkg/ && git commit -m "Add build artifacts"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
